CREATE TABLE "SYSTEM"."ESTUDANTES" 
   (	"ID_RGM" NUMBER(8,0) NOT NULL ENABLE, 
	"NC_NOMECOMPLETO" VARCHAR2(55 BYTE) NOT NULL ENABLE, 
	"DN_DATANASCIMENTO" DATE NOT NULL ENABLE, 
	"SB_SEXOBIOLOGICO" CHAR(1 BYTE) NOT NULL ENABLE, 
	"NP_NOMEPAI" VARCHAR2(55 BYTE), 
	"NM_NOMEMAE" VARCHAR2(55 BYTE), 
	"NR_NOMERESPONSAVEL" VARCHAR2(55 BYTE) NOT NULL ENABLE, 
	"TEL_TELEFONE" NUMBER(11,0), 
	"E_MAIL" VARCHAR2(100 BYTE), 
	 CONSTRAINT "ESTUDANTES_SB_SEXOBIOLOGICO_CK" CHECK (Sb_SexoBiologico in ('M','F')) ENABLE, 
	 CONSTRAINT "PK_ESTUDANTES" PRIMARY KEY ("ID_RGM", "TEL_TELEFONE", "E_MAIL")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "ESTUDANTES_ID_RGM_UN" UNIQUE ("ID_RGM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "ESTUDANTES_TEL_TELEFONE_UN" UNIQUE ("TEL_TELEFONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "ESTUDANTES_E_MAIL_UN" UNIQUE ("E_MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."ESTUDANTES"."ID_RGM" IS '(null)';

CREATE TABLE "SYSTEM"."MATRÍCULA" 
   (	"ID_RGM" NUMBER(8,0) NOT NULL ENABLE, 
	"CD_CLASSE" NUMBER(8,0) NOT NULL ENABLE, 
	"DT_MATRÍCULA" DATE NOT NULL ENABLE, 
	 CONSTRAINT "MATRÍCULA_CD_CLASSE_PK" PRIMARY KEY ("CD_CLASSE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "MATRÍCULA_ID_RGM_FK" FOREIGN KEY ("ID_RGM")
	  REFERENCES "SYSTEM"."ESTUDANTES" ("ID_RGM") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE TABLE "SYSTEM"."CLASSEESCOLAR" 
   (	"CD_CLASSE" NUMBER(8,0) NOT NULL ENABLE, 
	"NR_ANOLETIVO" NUMBER(4,0) NOT NULL ENABLE, 
	"NR_SERIE" NUMBER(2,0) NOT NULL ENABLE, 
	"TL_TURMALETRA" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"CD_ESCOLA" NUMBER(6,0) NOT NULL ENABLE, 
	"GE_GRAUESCOLAR" NUMBER(2,0) NOT NULL ENABLE, 
	"CD_PERÍODO" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "CLASSEESCOLAR_TL_TURMALETRA_PK" PRIMARY KEY ("TL_TURMALETRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "CLASSEESCOLAR_CD_CLASSE_FK" FOREIGN KEY ("CD_CLASSE")
	  REFERENCES "SYSTEM"."MATRÍCULA" ("CD_CLASSE") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ; 
